server:
 port: 9090

security:
 basic:
  enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:7654/spicinemas
    username: spiuser
    password: spiuser
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.use_sql_comments: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.hbm2ddl.auto: none