#Database Configuration
spring:
  profiles: test

  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: spiuser
    password: spiuser
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.use_sql_comments: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.hbm2ddl.auto: none


